name: Periodic Production Tests for the OpenAlchemy Editor

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  production-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: test/api/.venv
          key: ${{ runner.os }}-test-api-${{ hashFiles('test/api/Pipfile.lock') }}
      - name: install dependencies
        working-directory: ./test/api
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: Run tests
        working-directory: ./test
        run: |
          pipenv run test
