name: Periodic Production Tests for the OpenAlchemy Editor

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  production-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/test/Pipfile.lock') }}
      - name: Install dependencies
        working-directory: ./test
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      - name: Run tests
        working-directory: ./test
        run: |
          pipenv run test
